version: 2
jobs:
  build:
    docker:
      - image: python:3.4.2
    steps:
      - checkout
      - run: python --version
  test1:
    docker:
      - image: python:3.4.2
    steps:
      - checkout
      - run: python --version
  test2:
    docker:
      - image: python:2.7.0
    steps:
      - checkout
      - run: python --version
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test1
      - test2
      - test3
