version: 2
jobs:
  build:
    docker:
      - image: python:3.4.2
    steps:
      - checkout
      - run: echo build
  test1:
    docker:
      - image: python:3.4.2
    steps:
      - run: echo ${CIRCLE_PR_NUMBER}
      - checkout
      - run: python --version
  test2:
    docker:
      - image: python:2.7.13
    steps:
      - run: apt-get update && apt-get install jq
      - run: python --version
      - run: echo 'export CIRCLE_PR_NUMBER="${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}"' >> $BASH_ENV
      - run: echo $CIRCLE_PR_NUMBER
      - run: curl "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pulls/${CIRCLE_PR_NUMBER}?access_token=${GITHUB_TOKEN}" | jq .base.ref | tr -d '"'
      # - run: curl ${CIRCLE_PULL_REQUEST}?access_token=${GITHUB_TOKEN} |jq .base.ref
  hold:
    docker:
      - image: python:3.4.2
    steps:
      - checkout
      - run: echo hold
  deploy:
    machine: True
    steps:
      - run: echo deploy

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test1
      - test2
