version: 2
jobs:
  build:
    docker:
      - image: python:3.4.2
    steps:
      - checkout
  test1:
    docker:
      - image: python:3.4.2
    steps:
      - checkout
      - run: echo test1
  test2:
    docker:
      - image: python:3.4.2
    steps:
      - checkout
      - run: echo test2
  test3:
    docker:
      - image: python:3.4.2
    steps:
      - checkout
      - run: echo test3
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test1
      - test2
      - test3
